# Generated by Django 4.2.7 on 2023-12-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
