# Generated by Django 4.2.7 on 2023-12-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='degree',
        ),
    ]
