# Generated by Django 4.2.7 on 2023-12-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_education_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(default='master', max_length=200),
            preserve_default=False,
        ),
    ]
